app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^dologin/$',views.dologin,name='dologin'),
    url(r'^about/$',views.about,name='about'),
    url(r'^new/$',views.new,name='new'),
    url(r'^newlist/$',views.newlist,name='newlist'),
    url(r'^share/$',views.share,name='share'),
    url(r'^login/$',views.login,name='login'),
    url(r'^send/$',views.send,name='send'),
    url(r'^register/$',views.register,name='register'),

    #后台登录
    url(r'^adminindex/$',views.adminindex,name='adminindex'),
    url(r'^adminmain/$',views.adminmain,name='adminmain'),

    # 后台跳转界面
    url(r'^add_article/$',views.add_article,name='add_article'),
    url(r'^add_category/$',views.add_category,name='add_category'),
    url(r'^add_flink/$',views.add_flink,name='add_flink'),
    url(r'^add_notice/$',views.add_notice,name='add_notice'),
    url(r'^article/$',views.article,name='article'),
    url(r'^category/$',views.category,name='category'),
    url(r'^comment/$',views.comment,name='comment'),
    url(r'^flink/$',views.flink,name='flink'),
    url(r'^loginlog/$',views.loginlog,name='loginlog'),
    url(r'^manage_user/$',views.manage_user,name='manage_user'),
    url(r'^notice/$',views.notice,name='notice'),
    url(r'^readset/$',views.readset,name='readset'),
    url(r'^setting/$',views.setting,name='setting'),
    url(r'^update_flink/$',views.update_flink,name='update_flink'),
    url(r'^update_category/$',views.update_category,name='update_category'),
    url(r'^update_article/$',views.update_article,name='update_article'),
    url(r'^savedate/$',views.savedate,name='savedate')
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('app.urls',namespace='app')),
]

templates/app/about.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>黑色个人博客HTML5模板</title>
<meta name="keywords" content="个人博客模板,博客模板,响应式" />
<meta name="description" content="个人博客模板，神秘、俏皮。" />
<link href="/static/css/base.css" rel="stylesheet">
<link href="/static/css/index.css" rel="stylesheet">
<link href="/static/css/media.css" rel="stylesheet">
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<div class="ibody">
  <header>
    <h1>{{ user.username }}的博客</h1>
    <h2>影子是一个会撒谎的精灵，它在虚空中流浪和等待被发现之间;在存在与不存在之间....</h2>
    <div class="logo"><a href="{% url 'app:dologin' %}"></a></div>
    <nav id="topnav"><a href="{% url 'app:dologin' %}">首页</a><a href="{% url 'app:about' %}">关于我</a><a
                href="{% url 'app:newlist' %}">我的日记</a><a href="{% url 'app:share' %}">分享</a><a
                href="{% url 'app:new' %}">生活</a></nav>
  </header>
  <article>
    <h3 class="about_h">您现在的位置是：<a href="{% url 'app:dologin' %}">首页</a>><a href="{% url 'app:about' %}">关于我</a></h3>
    <div class="about">
      <h2>Just about me</h2>
      <ul>
        <p>杨青，女，一个80后草根女站长！09年入行，从业已经有三四年。从搬砖一样的生活方式换成了现在有“单”而居的日子。当然这个单不是单身的单，跟我的职业相比，爱情脱单并不是问题！虽然极尽苛刻的征婚条件但也远不及客户千奇百怪的要求。告别了朝九晚五，躲过了风吹日晒，虽然不再有阶梯式的工资，但是偶尔可以给自己放放假，挽着老公，一起轻装旅行。</p>
        <p> 人生就是一个得与失的过程，而我却是一个幸运者，得到的永远比失去的多。生活的压力迫使我放弃了轻松的前台接待，放弃了体面的编辑，换来虽有些蓬头垢面的工作，但是我仍然很享受那些熬得只剩下黑眼圈的日子，因为我在学习使用Photoshop、Flash、Dreamweaver、ASP、PHP、JSP...中激发了兴趣，然后越走越远....</p>
        <p>在这条路上，我要感谢三个人，第一个是我从事编辑的老板，是他给了我充分学习研究div的时间，第二个人是我的老师，如果不是街上的一次偶遇，如果不是因为我正缺钱，我不会去强迫自己做不会的事情，但是金钱的诱惑实在是抵挡不了，于是我选择了“接招”，东拼西凑的把一个网站做好了，当时还堪称佳作的网站至今已尘归尘土归土了。第三个人，我总说他是我的伯乐，因为我当初应聘技术员的时候，我说我什么都不会，但是他却给了我机会，而我就牢牢的把握了那次机会，直到现在如果不是我主动把域名和空间转出来，我会一直霸占着公司资源，免费下去（可我就偏偏不是喜欢爱占便宜的人，总感觉欠了就得还）...</p>
        <p> 还要特别感谢一个人，是我的老公。他是我的百科，我不会的，他会，最后我还是不会。博客能做到今天这样，一半都有他的功劳。他不仅仅支持我的事业作为我有力的经济后盾，还毫无怨言的包容我所有工作、生活当中有理无理的坏脾气，曾经我是多么有自己原则的一个人，但是遇到他，打破了我自己毕生坚持的原则，喜欢一句话“冥冥中该来则来，无处可逃”。 </p>
      </ul>
      <h2>About my blog</h2>
      <ul class="blog_a">
        <p>域  名：www.yangqq.com 创建于2011年01月12日 <a href="http://www.net.cn/domain/" class="blog_link" target="_blank">注册域名</a><a class="blog_link" href="http://koubei.baidu.com/womc/s/www.yangqq.com" target="_blank">邀你点评</a></p>
        <p>服务器：阿里云服务器<a href="http://www.aliyun.com/product/ecs/?ali_trackid=2:mm_11085263_4976026_15602229:1389838528_3k2_34164590" class="blog_link" target="_blank">购买空间</a><a href="/jstt/web/2014-01-18/644.html" target="_blank" class="blog_link" >参考我的空间配置</a></p>
        <p>程  序：PHP 帝国CMS7.0</p>
        <p>微信公众号：wwwyangqqcom</p>
      </ul>
    </div>
  </article>
  <aside>
    <div class="avatar"><a href="{% url 'app:about' %}"><img src="{{ url }}" style="margin: -100px auto; width: 160px; height: 160px; border-radius: 100%; "><span>关于{{ user.username }}</span></a></div>
    <div class="topspaceinfo">
      <h1>执子之手，与子偕老</h1>
      <p>于千万人之中，我遇见了我所遇见的人....</p>
    </div>
    <div class="about_c">
      <p>职业：{{ user.profession }} </p>
      <p>籍贯：{{ user.native_place }}</p>
      <p>电话：{{ user.phone }}</p>
      <p>邮箱：{{ user.email }}</p>
    </div>
  </aside>
  <script src="/static/js/silder.js"></script>
  <div class="clear"></div>
  <!-- 清除浮动 --> 
</div>
</body>
</html>

templates/app/dologin.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    {% block css %}
        <meta charset="utf-8">
        <title>个人主页</title>
        <meta name="keywords" content="个人博客模板,博客模板,响应式"/>
        <meta name="description" content="个人博客模板，神秘、俏皮。"/>
        <link href="/static/css/base.css" rel="stylesheet">
        <link href="/static/css/index.css" rel="stylesheet">
        <link href="/static/css/media.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    {% endblock %}

</head>
<body>

<div class="ibody">
    <header>
        <h1>{{ users.username }}的博客</h1>
        <h2>影子是一个会撒谎的精灵，它在虚空中流浪和等待被发现之间;在存在与不存在之间....</h2>
        <div class="logo"><a href="{% url 'app:dologin' %}"></a></div>
        <nav id="topnav"><a href="{% url 'app:dologin' %}">首页</a><a href="{% url 'app:about' %}">关于我</a><a
                href="{% url 'app:newlist' %}">我的日记</a><a href="{% url 'app:share' %}">分享</a><a
                href="{% url 'app:new' %}">生活</a></nav>
    </header>
    <article>
        <div class="banner">
            <ul class="texts">
                <p>The best life is use of willing attitude, a happy-go-lucky life. </p>
                <p>最好的生活是用心甘情愿的态度，过随遇而安的生活。</p>
            </ul>
        </div>
        <div class="bloglist">
            {% for blog in blogs %}
                        <div class="blogs">
                            <h3><a href="/">{{ blog.title }}</a></h3>
                            <ul>
                                <div style="height:100px;overflow: hidden">
                                    {{ blog.content }}
                                </div>
                                <a href="/" target="_blank" class="readmore" name="looked">阅读全文&gt;&gt;</a>
                            </ul>
                            <p class="autor">
                                <span>作者：</span>{{ users.username }}
                                <span>分类：【<a href="/">{{ blog.category }}</a>】</span>
                                <span>浏览（<a href="/">{{ blog.click_nums }}</a>）</span>
                                <span>评论（<a href="/">{{ comm.comment_nums }}</a>）</span>
                                <span>发表于：{{ blog.modify_time }}</span>
                            </p>
                            <div class="dateview" style="width: 300px;overflow: hidden">{{ blog.category }}</div>
                        </div>
            {% endfor %}
    </article>
    {% block body %}
        <aside>
            <div class="avatar"><a href="{% url 'app:about' %}"> <img src="{{ url }}" style="margin: -100px auto; width: 160px; height: 160px; border-radius: 100%; "> <span>关于{{ users.username }}</span></a></div>
            <div class="topspaceinfo">
                <h1>江湖就是人情世故</h1>
                <p>你若要喜爱你自己的价值，你就得给世界创造价值。</p>
            </div>
            <div class="about_c">
                <p>职业：{{ users.profession }} </p>
                <p>籍贯：{{ users.native_place }}</p>
                <p>电话：{{ users.phone }}</p>
                <p>邮箱：{{ users.email }}</p>
            </div>
            <div class="bdsharebuttonbox"><a href="https://qzone.qq.com/" class="bds_qzone" data-cmd="qzone"
                                             title="分享到QQ空间"></a><a href="https://weibo.com/" class="bds_tsina"
                                                                    data-cmd="tsina" title="分享到新浪微博"></a><a
                    href="http://t.qq.com/" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a
                    href="http://www.renren.com/" class="bds_renren" data-cmd="renren" title="分享到人人网"></a></div>
            <div class="tj_news">
                <h2>
                    <p class="tj_t1">最新文章</p>
                </h2>
                <ul>
                    {% for blog in blogs %}
                        <li>
                            <a href="/">{{ blog.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <h2>
                    <p class="tj_t2">推荐文章</p>
                </h2>
                <ul>
                    {% for blog in blogs %}
                        <li><a href="/">{{ blog.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="links">
                <h2>
                    <p>友情链接</p>
                </h2>
                <ul>
                    <li><a href="https://blog.csdn.net/qq_42936274">个人博客</a></li>
                    <li><a href="http://www.python88.com/">python中国社区</a></li>
                </ul>
            </div>
            <div class="copyright">
                <ul>
                    <p> Design by <a href="/">DanceSmile</a></p>
                    <p>豫ICP备18040197号-1</p>
                    </p>
                </ul>
            </div>
        </aside>
    {% endblock %}
    {% for blog in blogs %}
        <script src="/static/js/silder.js" type="text/javascript">
            var looked = document.getElementsByName('looked')
            var num = document.getElementsByName('{{ blog.click_nums }}')
            looked.onclick = function () {
                num += 1
            }
            $(function () {
                var more = $('')
            })
        </script>
    {% endfor %}
    <div class="clear"></div>
    <!-- 清除浮动 -->
</div>
<div style="text-align:center;">
</div>
</body>
</html>

templates/app/new.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>个人博客</title>
    <meta name="keywords" content="个人博客模板,博客模板,响应式"/>
    <meta name="description" content="个人博客模板，神秘、俏皮。"/>
    <link href="/static/css/base.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/media.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<div class="ibody">
    <header>
        <h1>{{ user.username }}的博客</h1>
        <h2>影子是一个会撒谎的精灵，它在虚空中流浪和等待被发现之间;在存在与不存在之间....</h2>
        <div class="logo"><a href="{% url 'app:dologin' %}"></a></div>
        <nav id="topnav"><a href="{% url 'app:dologin' %}">首页</a><a href="{% url 'app:about' %}">关于我</a><a
                href="{% url 'app:newlist' %}">我的日记</a><a href="{% url 'app:share' %}">分享</a><a
                href="{% url 'app:new' %}">生活</a></nav>
    </header>
    <article>
        <h2 class="about_h">您现在的位置是：<a href="{% url 'app:dologin' %}">首页</a>><a href="{% url 'app:share' %}">分享</a>><a
                href="{% url 'app:new' %}">生活</a></h2>
        <div class="index_about">
            {% for blog in blogs %}
                <h2 class="c_titile">{{ blog.title }}</h2>
                <p class="box_c"><span class="d_time">发布时间：{{ blog.modify_time }}</span><span>编辑：</span><span>浏览{{ blog.click_nums }}</span><span>评论览（14）</span>
                </p>
                <ul class="infos">
                    <p>
                        2014第二版黑色Html5个人博客模板主题《如影随形》，如精灵般的影子会给人一种神秘的感觉。一张剪影图黑白搭配，如果整个网站用黑白灰三色，会显得比较太过沉重，于是，在选择亮色方面，用以红为主色，蓝为辅色。这样就铺上了一些神秘甚至有些俏皮的元素。</p>
                    <p>如果你更喜欢用蓝色或者绿色，这也不错，替换关键的颜色值就行了，推荐颜色值：<img src="/static/images/color.jpg" alt="黑色Html5个人博客模板"></p>
                    <p>Html5响应式两栏布局，LOGO重点突出，首页推荐文章列表以Logo中轴线为时间轴，鼠标Hover触发时间轴左侧栏显示文章发布时间，文字banner动画均以css3代码来实现效果。</p>
                    <p><b>首页效果图：</b></p>
                    <p><img src="/static/images/xgt.jpg" alt="黑色Html5个人博客模板"></p>
                    <p><b>移动设备和平板电脑浏览效果：</b></p>
                    <p><img src="/static/images/ltpic.jpg" alt="黑色Html5个人博客模板"></p>
                    <p><img src="/static/images/col.jpg" alt="黑色Html5个人博客模板"></p>
                </ul>
                <div class="keybq">
                    <p><span>关键字词</span>：黑色,个人博客,时间轴,响应式</p>
                </div>
                <div class="nextinfo">
                    <p>上一篇：<a href="/news/s/2013-09-04/606.html">程序员应该如何高效的工作学习</a></p>
                    <p>下一篇：<a href="/news/s/2013-10-21/616.html">柴米油盐的生活才是真实</a></p>
                </div>
                <div class="otherlink">
                    <h2>相关文章</h2>
                    <ul>
                        <li><a href="/news/s/2013-07-25/524.html" title="现在，我相信爱情！">现在，我相信爱情！</a></li>
                        <li><a href="/newstalk/mood/2013-07-24/518.html" title="我希望我的爱情是这样的">我希望我的爱情是这样的</a></li>
                        <li><a href="/newstalk/mood/2013-07-02/335.html" title="有种情谊，不是爱情，也算不得友情">有种情谊，不是爱情，也算不得友情</a>
                        </li>
                        <li><a href="/newstalk/mood/2013-07-01/329.html" title="世上最美好的爱情">世上最美好的爱情</a></li>
                        <li><a href="/news/read/2013-06-11/213.html" title="爱情没有永远，地老天荒也走不完">爱情没有永远，地老天荒也走不完</a></li>
                        <li><a href="/news/s/2013-06-06/24.html" title="爱情的背叛者">爱情的背叛者</a></li>
                    </ul>
                </div>
            {% endfor %}

        </div>
    </article>
    <aside>
        <div class="rnav">
            <li class="rnav1 "><a href="/">日记</a></li>
            <li class="rnav2 "><a href="/">欣赏</a></li>
            <li class="rnav3 "><a href="/">程序人生</a></li>
            <li class="rnav4 "><a href="/">经典语录</a></li>
        </div>
        <div class="ph_news">
            <h2>
                <p>点击排行</p>
            </h2>
            <ul class="ph_n">
                {% for blog in blogs %}
                <li><span class="num1">1</span><a href="/">{{ blog.title }}</a></li>
                {% endfor %}
            </ul>
            <h2>
                <p>栏目推荐</p>
            </h2>
            <ul>
                {% for blog in blogs %}
                <li><a href="/">{{ blog.title }}</a></li>
                {% endfor %}
            </ul>
            <h2>
                <p>最新评论</p>
            </h2>
            <ul class="pl_n">
                <dl>
                    <dt><img src="/static/images/s8.jpg"></dt>
                    <dt></dt>
                    <dd>DanceSmile
                        <time>49分钟前</time>
                    </dd>
                    <dd><a href="/">文章非常详细，我很喜欢.前端的工程师很少，我记得几年前yahoo花高薪招聘前端也招不到</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/s7.jpg"></dt>
                    <dt></dt>
                    <dd>yisa
                        <time>2小时前</time>
                    </dd>
                    <dd><a href="/">我手机里面也有这样一个号码存在</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/s6.jpg"></dt>
                    <dt></dt>
                    <dd>小林博客
                        <time>8月7日</time>
                    </dd>
                    <dd><a href="/">博客色彩丰富，很是好看</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/003.jpg"></dt>
                    <dt></dt>
                    <dd>DanceSmile
                        <time>49分钟前</time>
                    </dd>
                    <dd><a href="/">文章非常详细，我很喜欢.前端的工程师很少，我记得几年前yahoo花高薪招聘前端也招不到</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/002.jpg"></dt>
                    <dt></dt>
                    <dd>yisa
                        <time>2小时前</time>
                    </dd>
                    <dd><a href="/">我手机里面也有这样一个号码存在</a></dd>
                </dl>
            </ul>
            <h2>
                <p>最近访客</p>
                <ul>
                    <img src="/static/images/vis.jpg"><!-- 直接使用“多说”插件的调用代码 -->
                </ul>
            </h2>
        </div>
        <div class="copyright">
            <ul>
                <p> Design by <a href="/">DanceSmile</a></p>
                <p>蜀ICP备11002373号-1</p>
                </p>
            </ul>
        </div>
    </aside>
    <script src="/static/js/silder.js"></script>
    <div class="clear"></div>
    <!-- 清除浮动 -->
</div>
</body>
</html>

templates/app/newlist.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>黑色个人博客HTML5模板</title>
    <meta name="keywords" content="个人博客模板,博客模板,响应式"/>
    <meta name="description" content="个人博客模板，神秘、俏皮。"/>
    <link href="/static/css/base.css" rel="stylesheet">
    <link href="/static/css/index.css" rel="stylesheet">
    <link href="/static/css/media.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<div class="ibody">
    <header>
        <h1>如影随形</h1>
        <h2>影子是一个会撒谎的精灵，它在虚空中流浪和等待被发现之间;在存在与不存在之间....</h2>
        <div class="logo"><a href="{% url 'app:dologin' %}"></a></div>
        <nav id="topnav"><a href="{% url 'app:dologin' %}">首页</a><a href="{% url 'app:about' %}">关于我</a><a
                href="{% url 'app:newlist' %}">我的日记</a><a href="{% url 'app:share' %}">分享</a><a
                href="{% url 'app:new' %}">生活</a></nav>
    </header>
    <article>
        <h2 class="about_h">您现在的位置是：<a href="{% url 'app:dologin' %}">首页</a>><a href="{% url 'app:newlist' %}">我的日记</a>
        </h2>
        <div class="bloglist">

                <div class="newblog">
                    <ul>
                        <h3><a href="/">个人博客从简不繁</a></h3>
                        <div class="autor"><span>作者：{{ user.username }}</span><span>分类：[<a href="/">{{ blog.category }}</a>]</span><span>浏览（<a
                                href="/">{{ blog.click_nums }}</a>）</span><span>评论（<a href="/">0</a>）</span></div>
                        <p>{{ blog.content }} <a href="/" target="_blank" class="readmore">全文</a></p>
                    </ul>
                    <figure><img src="/static/images/001.jpg"></figure>
                    <div class="dateview">{{ blog.modify_time }}</div>
                </div>

        </div>
        <div class="page"><a title="Total record"><b>113</b></a><b>1</b><a href="/">2</a><a href="/">3</a><a
                href="/">4</a><a href="/">5</a><a href="/">&gt;</a><a href="/">&gt;&gt;</a></div>
    </article>
    <aside>
        <div class="rnav">
            <li class="rnav1 "><a href="/">日记</a></li>
            <li class="rnav2 "><a href="/">欣赏</a></li>
            <li class="rnav3 "><a href="/">程序人生</a></li>
            <li class="rnav4 "><a href="/">经典语录</a></li>
        </div>
        <div class="ph_news">
            <h2>
                <p>点击排行</p>
            </h2>
            <ul class="ph_n">
                <li><span class="num1">1</span><a href="/">有一种思念，是淡淡的幸福,一个心情一行文字</a></li>
                <li><span class="num2">2</span><a href="/">励志人生-要做一个潇洒的女人</a></li>
                <li><span class="num3">3</span><a href="/">女孩都有浪漫的小情怀――浪漫的求婚词</a></li>
                <li><span>4</span><a href="/">Green绿色小清新的夏天-个人博客模板</a></li>
                <li><span>5</span><a href="/">女生清新个人博客网站模板</a></li>
                <li><span>6</span><a href="/">Wedding-婚礼主题、情人节网站模板</a></li>
                <li><span>7</span><a href="/">Column 三栏布局 个人网站模板</a></li>
                <li><span>8</span><a href="/">时间煮雨-个人网站模板</a></li>
                <li><span>9</span><a href="/">花气袭人是酒香―个人网站模板</a></li>
            </ul>
            <h2>
                <p>栏目推荐</p>
            </h2>
            <ul>
                <li><a href="/">有一种思念，是淡淡的幸福,一个心情一行文字</a></li>
                <li><a href="/">励志人生-要做一个潇洒的女人</a></li>
                <li><a href="/">女孩都有浪漫的小情怀――浪漫的求婚词</a></li>
                <li><a href="/">Green绿色小清新的夏天-个人博客模板</a></li>
                <li><a href="/">女生清新个人博客网站模板</a></li>
                <li><a href="/">Wedding-婚礼主题、情人节网站模板</a></li>
                <li><a href="/">Column 三栏布局 个人网站模板</a></li>
                <li><a href="/">时间煮雨-个人网站模板</a></li>
                <li><a href="/">花气袭人是酒香―个人网站模板</a></li>
            </ul>
            <h2>
                <p>最新评论</p>
            </h2>
            <ul class="pl_n">
                <dl>
                    <dt><img src="/static/images/s8.jpg"></dt>
                    <dt></dt>
                    <dd>DanceSmile
                        <time>49分钟前</time>
                    </dd>
                    <dd><a href="/">文章非常详细，我很喜欢.前端的工程师很少，我记得几年前yahoo花高薪招聘前端也招不到</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/s7.jpg"></dt>
                    <dt></dt>
                    <dd>yisa
                        <time>2小时前</time>
                    </dd>
                    <dd><a href="/">我手机里面也有这样一个号码存在</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/s6.jpg"></dt>
                    <dt></dt>
                    <dd>小林博客
                        <time>8月7日</time>
                    </dd>
                    <dd><a href="/">博客色彩丰富，很是好看</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/003.jpg"></dt>
                    <dt></dt>
                    <dd>DanceSmile
                        <time>49分钟前</time>
                    </dd>
                    <dd><a href="/">文章非常详细，我很喜欢.前端的工程师很少，我记得几年前yahoo花高薪招聘前端也招不到</a></dd>
                </dl>
                <dl>
                    <dt><img src="/static/images/002.jpg"></dt>
                    <dt></dt>
                    <dd>yisa
                        <time>2小时前</time>
                    </dd>
                    <dd><a href="/">我手机里面也有这样一个号码存在</a></dd>
                </dl>
            </ul>
            <h2>
                <p>最近访客</p>
                <ul>
                    <img src="/static/images/vis.jpg"><!-- 直接使用“多说”插件的调用代码 -->
                </ul>
            </h2>
        </div>
        <div class="copyright">
            <ul>
                <p> Design by <a href="/">DanceSmile</a></p>
                <p>蜀ICP备11002373号-1</p>
                </p>
            </ul>
        </div>
    </aside>
    <script src="/static/js/silder.js"></script>
    <div class="clear"></div>
    <!-- 清除浮动 -->
</div>
</body>
</html>